FROM microsoft/dotnet:2.2-aspnetcore-runtime AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM microsoft/dotnet:2.2-sdk AS build
WORKDIR /src
COPY ["client.csproj", "client/"]
RUN dotnet restore "client/client.csproj"
WORKDIR "/src/client/"
COPY . .
RUN dotnet build "client.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "client.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "client.dll"]