apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: aspnet-svc-dep
  #namespace: cupcake
  labels:
    app: cupcake
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cupcake-aspnet
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: cupcake-aspnet
    spec:
      containers:
        - name: aspnetk-svc
          image: riskfirstacr.azurecr.io/cupcake/aspnet-svc:1.0
          ports:
            - containerPort: 80
          env:
          - name: CUPCAKE_DBSERVER
            valueFrom:
              configMapKeyRef:
                name: cupcake-config
                key: dbServer
          - name: CUPCAKE_DBNAME
            valueFrom:
              configMapKeyRef:
                name: cupcake-config
                key: dbName
          - name: CUPCAKE_DBUSER
            valueFrom:
              configMapKeyRef:
                name: cupcake-config
                key: dbUser
          - name: CUPCAKE_DBPASSWORD
            valueFrom:
              configMapKeyRef:
                name: cupcake-config
                key: dbPass

---
apiVersion: v1
kind: Service
metadata:
  name: aspnet-svc
  #namespace: cupcake
  labels:
    app: cupcake
spec:
  type: ClusterIP 
  selector:
    app: cupcake-aspnet
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP