FROM microsoft/dotnet:2.2-aspnetcore-runtime AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM microsoft/dotnet:2.2-sdk AS build
WORKDIR /src
COPY ["cupcake_client.csproj", "cupcake_client/"]
RUN dotnet restore "cupcake_client/cupcake_client.csproj"
WORKDIR "/src/cupcake_client/"
COPY . .
RUN dotnet build "cupcake_client.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "cupcake_client.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "cupcake_client.dll"]