FROM microsoft/dotnet:2.2-aspnetcore-runtime AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM microsoft/dotnet:2.2-sdk AS build
WORKDIR /src
COPY ["cupcake_aspnet.csproj", "cupcake_aspnet/"]
RUN dotnet restore "cupcake_aspnet/cupcake_aspnet.csproj"
WORKDIR "/src/cupcake_aspnet/"
COPY . .
RUN dotnet build "cupcake_aspnet.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "cupcake_aspnet.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "cupcake_aspnet.dll"]