FROM microsoft/dotnet:2.2-aspnetcore-runtime AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM microsoft/dotnet:2.2-sdk AS build
WORKDIR /src
COPY ["cupcake_aspnet3.csproj", "cupcake_aspnet3/"]
RUN dotnet restore "cupcake_aspnet3/cupcake_aspnet3.csproj"
WORKDIR "/src/cupcake_aspnet3/"
COPY . .
RUN dotnet build "cupcake_aspnet3.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "cupcake_aspnet3.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "cupcake_aspnet3.dll"]